# Generated by Django 5.2.10 on 2026-01-14 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(default='1.0', max_length=10, verbose_name='Versiyon')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif Reçete mi?')),
                ('description', models.TextField(blank=True, verbose_name='Üretim Notları')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Müşteri/Firma Adı')),
                ('tax_number', models.CharField(blank=True, max_length=20, verbose_name='Vergi No')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True, verbose_name='Adres')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Adı')),
                ('last_name', models.CharField(max_length=50, verbose_name='Soyadı')),
                ('employee_id', models.CharField(max_length=20, unique=True, verbose_name='Sicil No')),
                ('skill_set', models.CharField(blank=True, max_length=100, verbose_name='Uzmanlık Alanı')),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Vardiya Adı')),
                ('start_time', models.TimeField(verbose_name='Başlangıç Saati')),
                ('end_time', models.TimeField(verbose_name='Bitiş Saati')),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Depo Adı')),
                ('warehouse_type', models.CharField(choices=[('RAW', 'Hammadde Deposu'), ('WIP', 'Ara Stok (İşlem Sırası)'), ('FINAL', 'Mamul Deposu'), ('SCRAP', 'Hurda Deposu')], max_length=20, verbose_name='Depo Tipi')),
            ],
        ),
        migrations.CreateModel(
            name='WorkCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Üretim Merkezi Kodu')),
                ('name', models.CharField(max_length=100, verbose_name='Üretim Merkezi Adı')),
                ('daily_capacity_hours', models.DecimalField(decimal_places=2, default=8.0, max_digits=5, verbose_name='Günlük Kapasite (Saat)')),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=100.0, max_digits=10, verbose_name='Saatlik Maliyet (TL/Saat)')),
                ('efficiency_factor', models.DecimalField(decimal_places=2, default=0.9, max_digits=3, verbose_name='Verimlilik Faktörü')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Kategori Kodu')),
                ('name', models.CharField(max_length=100, verbose_name='Kategori Adı')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='products.category', verbose_name='Üst Kategori')),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategoriler',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField(verbose_name='İşlem Sırası')),
                ('description', models.CharField(max_length=255, verbose_name='İşlem Açıklaması')),
                ('setup_time', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Hazırlık Süresi (Dakika)')),
                ('cycle_time', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='İşlem Süresi (Dakika/Adet)')),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='products.bom', verbose_name='İlgili Reçete')),
                ('work_center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.workcenter', verbose_name='Üretim Merkezi')),
            ],
            options={
                'verbose_name': 'Operasyon',
                'verbose_name_plural': 'Operasyonlar',
                'ordering': ['step_number'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Ürün Adı')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='Stok Kodu (SKU)')),
                ('product_type', models.CharField(choices=[('RAW', 'Raw Material (Hammadde)'), ('SEMI', 'Semi-Finished (Yarı Mamul)'), ('FINAL', 'Finished Good (Mamul)'), ('TRAD', 'Trading Good (Ticari Mal)'), ('CONS', 'Consumable (Sarf Malzeme)'), ('MRO', 'MRO - Maintenance & Repair (İşletme Malzemesi)'), ('SRVC', 'Service (Hizmet)'), ('SCRP', 'Scrap/Waste (Hurda/Atık)'), ('PACK', 'Packaging (Paketleme Malzemesi)')], default='RAW', max_length=10, verbose_name='Ürün Tipi')),
                ('price', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='Birim Fiyat')),
                ('stock_quantity', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='Stok Miktarı')),
                ('unit_of_measure', models.CharField(choices=[('UNIT', 'Adet'), ('KG', 'Kilogram'), ('LT', 'Litre'), ('METER', 'Metre'), ('M2', 'Metrekare')], default='UNIT', max_length=10, verbose_name='Ölçü Birimi')),
                ('lead_time', models.PositiveIntegerField(default=0, verbose_name='Tedarik Süresi (Gün)')),
                ('min_stock_level', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='Minimum Stok Seviyesi')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category')),
            ],
        ),
        migrations.CreateModel(
            name='BOMItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=5, max_digits=20, verbose_name='Miktar')),
                ('scrap_factor', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Fire Oranı (%)')),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='products.bom', verbose_name='Ürün Ağacı')),
                ('child_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product', verbose_name='Bileşen')),
            ],
        ),
        migrations.AddField(
            model_name='bom',
            name='parent_product',
            field=models.OneToOneField(limit_choices_to={'product_type__in': ['SEMI', 'FINAL']}, on_delete=django.db.models.deletion.CASCADE, related_name='bom_header', to='products.product', verbose_name='Üretilecek Ürün'),
        ),
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_quantity', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Planlanan Miktar')),
                ('actual_quantity', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='Gerçekleşen Miktar')),
                ('start_date', models.DateField(verbose_name='Planlanan Başlangıç')),
                ('due_date', models.DateField(verbose_name='Teslim Tarihi (Deadline)')),
                ('status', models.CharField(choices=[('DRAFT', 'Taslak'), ('PLANNED', 'Planlandı'), ('IN_PROGRESS', 'Üretimde'), ('COMPLETED', 'Tamamlandı'), ('CANCELLED', 'İptal Edildi')], default='DRAFT', max_length=20, verbose_name='Durum')),
                ('product', models.ForeignKey(limit_choices_to={'product_type__in': ['SEMI', 'FINAL']}, on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Üretilecek Ürün')),
            ],
            options={
                'verbose_name': 'Üretim Emri',
                'verbose_name_plural': 'Üretim Emirleri',
            },
        ),
        migrations.CreateModel(
            name='QualityCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_quantity', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Kontrol Edilen Miktar')),
                ('approved_quantity', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Onaylanan Miktar')),
                ('rejected_quantity', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Reddedilen Miktar')),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='Red Nedeni')),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_checks', to='products.productionorder', verbose_name='Üretim Emri')),
            ],
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Sipariş Miktarı')),
                ('order_date', models.DateField(auto_now_add=True, verbose_name='Sipariş Tarihi')),
                ('delivery_date', models.DateField(verbose_name='Söz Verilen Teslim Tarihi')),
                ('is_shipped', models.BooleanField(default=False, verbose_name='Sevk Edildi mi?')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='products.customer', verbose_name='Müşteri')),
                ('product', models.ForeignKey(limit_choices_to={'product_type': 'FINAL'}, on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Sipariş Edilen Ürün')),
            ],
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Değişim Miktarı')),
                ('transaction_type', models.CharField(choices=[('IN', 'Giriş (Satın Alma/Üretim)'), ('OUT', 'Çıkış (Satış/Sarf)'), ('SCRAP', 'Hurda Ayırımı'), ('ADJ', 'Sayım Farkı (Düzeltme)')], max_length=10, verbose_name='İşlem Tipi')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Notlar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='İşlem Tarihi')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='products.product', verbose_name='Ürün')),
                ('warehouse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.warehouse', verbose_name='Depo')),
            ],
            options={
                'verbose_name': 'Stok Hareketi',
                'verbose_name_plural': 'Stok Hareketleri',
            },
        ),
        migrations.CreateModel(
            name='ProductionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_duration', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Planlanan Süre (Dakika)')),
                ('actual_duration', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Gerçekleşen Süre (Dakika)')),
                ('quantity_produced', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Üretilen Miktar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
                ('operation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='products.operation', verbose_name='Yapılan Operasyon')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.employee', verbose_name='Operatör')),
                ('production_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='products.productionorder', verbose_name='Üretim Emri')),
                ('shift', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.shift', verbose_name='Vardiya')),
                ('work_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_logs', to='products.workcenter', verbose_name='Üretim Merkezi')),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_type', models.CharField(choices=[('PREV', 'Periyodik Bakım'), ('REPAIR', 'Arıza Onarımı'), ('UPGRADE', 'İyileştirme (Kaizen)')], max_length=10, verbose_name='Bakım Tipi')),
                ('downtime_minutes', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Duruş Süresi (Dakika)')),
                ('description', models.TextField(verbose_name='Yapılan İşlem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Bakım Tarihi')),
                ('work_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='products.workcenter', verbose_name='Üretim Merkezi')),
            ],
        ),
    ]
