# Generated by Django 5.2.10 on 2026-01-15 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Hata Kodu')),
                ('description', models.CharField(max_length=255, verbose_name='Hata Açıklaması')),
                ('category', models.CharField(choices=[('MECHANICAL', 'Mekanik'), ('ELECTRICAL', 'Elektriksel'), ('OPERATOR', 'Operatör Kaynaklı'), ('EXTERNAL', 'Dış Kaynaklı')], max_length=20, verbose_name='Hata Kategorisi')),
            ],
        ),
        migrations.AddField(
            model_name='maintenance',
            name='reason',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.maintenancereason', verbose_name='Arıza Nedeni'),
        ),
        migrations.CreateModel(
            name='QualityParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Parametre Adı')),
                ('min_value', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Min. Değer')),
                ('max_value', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Max. Değer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_parameters', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='QualityMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measured_value', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Ölçülen Değer')),
                ('quality_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='products.qualitycheck')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.qualityparameter')),
            ],
        ),
    ]
