# Generated by Django 5.2.10 on 2026-01-15 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_maintenancereason_maintenance_reason_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bom',
            options={'verbose_name': 'Ürün Ağacı', 'verbose_name_plural': 'Ürün Ağaçları'},
        ),
        migrations.AlterModelOptions(
            name='bomitem',
            options={'verbose_name': 'Ürün Ağacı Kalemi', 'verbose_name_plural': 'Ürün Ağacı Kalemleri'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Müşteri', 'verbose_name_plural': 'Müşteriler'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Operatör', 'verbose_name_plural': 'Operatörler'},
        ),
        migrations.AlterModelOptions(
            name='maintenance',
            options={'verbose_name': 'Arıza Bakım Analizi', 'verbose_name_plural': 'Arıza Bakım Analizleri'},
        ),
        migrations.AlterModelOptions(
            name='maintenancereason',
            options={'verbose_name': 'Arıza Bakım Nedeni', 'verbose_name_plural': 'Arıza Bakım Nedenleri'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Üretim', 'verbose_name_plural': 'Üretimler'},
        ),
        migrations.AlterModelOptions(
            name='productionlog',
            options={'verbose_name': 'Üretim Kaydı', 'verbose_name_plural': 'Üretim Kayıtları'},
        ),
        migrations.AlterModelOptions(
            name='qualitycheck',
            options={'verbose_name': 'Kalite Kontrol', 'verbose_name_plural': 'Kalite Kontroller'},
        ),
        migrations.AlterModelOptions(
            name='qualitymeasurement',
            options={'verbose_name': 'Kalite Kontrol Ölçümü', 'verbose_name_plural': 'Kalite Kontrol Ölçümleri'},
        ),
        migrations.AlterModelOptions(
            name='qualityparameter',
            options={'verbose_name': 'Kalite Kontrol Detayı', 'verbose_name_plural': 'Kalite Kontrol Detayları'},
        ),
        migrations.AlterModelOptions(
            name='salesorder',
            options={'verbose_name': 'Sipariş Talebi', 'verbose_name_plural': 'Sipariş Talepleri'},
        ),
        migrations.AlterModelOptions(
            name='shift',
            options={'verbose_name': 'Vardiya', 'verbose_name_plural': 'Vardiyalar'},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'verbose_name': 'Depo', 'verbose_name_plural': 'Depolar'},
        ),
        migrations.AlterModelOptions(
            name='workcenter',
            options={'verbose_name': 'Üretim Merkezi', 'verbose_name_plural': 'Üretim Merkezleri'},
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category', verbose_name='Ürünler'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('RAW', 'Hammadde'), ('SEMI', 'Yarı Mamul'), ('FINAL', 'Mamul'), ('TRAD', 'Ticari Mal'), ('CONS', 'Sarf Malzeme'), ('MRO', 'İşletme Malzemesi'), ('SRVC', 'Hizmet'), ('SCRP', 'Hurda/Atık'), ('PACK', 'Paketleme Malzemesi')], default='RAW', max_length=10, verbose_name='Ürün Tipi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(max_length=50, unique=True, verbose_name='Stok Kodu'),
        ),
        migrations.AlterField(
            model_name='qualitymeasurement',
            name='quality_check',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='products.qualitycheck', verbose_name='Kalite Kontrol'),
        ),
    ]
